/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze.index'
import { Route as AnalyzeProcessingRouteImport } from './routes/analyze.processing'
import { Route as AnalyzeResultRouteImport } from './routes/analyze.result'
import { Route as AnalyzeReviewRouteImport } from './routes/analyze.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyzeRoute,
} as any)
const AnalyzeProcessingRoute = AnalyzeProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AnalyzeRoute,
} as any)
const AnalyzeResultRoute = AnalyzeResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AnalyzeRoute,
} as any)
const AnalyzeReviewRoute = AnalyzeReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AnalyzeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/analyze/processing': typeof AnalyzeProcessingRoute
  '/analyze/result': typeof AnalyzeResultRoute
  '/analyze/review': typeof AnalyzeReviewRoute
  '/analyze/': typeof AnalyzeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze/processing': typeof AnalyzeProcessingRoute
  '/analyze/result': typeof AnalyzeResultRoute
  '/analyze/review': typeof AnalyzeReviewRoute
  '/analyze': typeof AnalyzeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/analyze/processing': typeof AnalyzeProcessingRoute
  '/analyze/result': typeof AnalyzeResultRoute
  '/analyze/review': typeof AnalyzeReviewRoute
  '/analyze/': typeof AnalyzeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/analyze/processing'
    | '/analyze/result'
    | '/analyze/review'
    | '/analyze/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze/processing'
    | '/analyze/result'
    | '/analyze/review'
    | '/analyze'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/analyze/processing'
    | '/analyze/result'
    | '/analyze/review'
    | '/analyze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/analyze/processing': {
      id: '/analyze/processing'
      path: '/processing'
      fullPath: '/analyze/processing'
      preLoaderRoute: typeof AnalyzeProcessingRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/analyze/result': {
      id: '/analyze/result'
      path: '/result'
      fullPath: '/analyze/result'
      preLoaderRoute: typeof AnalyzeResultRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/analyze/review': {
      id: '/analyze/review'
      path: '/review'
      fullPath: '/analyze/review'
      preLoaderRoute: typeof AnalyzeReviewRouteImport
      parentRoute: typeof AnalyzeRoute
    }
  }
}

interface AnalyzeRouteChildren {
  AnalyzeProcessingRoute: typeof AnalyzeProcessingRoute
  AnalyzeResultRoute: typeof AnalyzeResultRoute
  AnalyzeReviewRoute: typeof AnalyzeReviewRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
}

const AnalyzeRouteChildren: AnalyzeRouteChildren = {
  AnalyzeProcessingRoute: AnalyzeProcessingRoute,
  AnalyzeResultRoute: AnalyzeResultRoute,
  AnalyzeReviewRoute: AnalyzeReviewRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
}

const AnalyzeRouteWithChildren =
  AnalyzeRoute._addFileChildren(AnalyzeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
