export type Language = "en" | "ar";

export const copy = {
  en: {
    nav: { how: "How it works", analyze: "Analyze", about: "About" },
    hero: { 
      eyebrow: "Document intelligence, redefined", 
      title: "Smart loan eligibility intelligence.", 
      body: "Upload your loan application and let MUSTAWFI analyze, validate, and transform your application into an intelligent machine-learning prediction.", 
      primary: "Analyze application", 
      secondary: "How it works" 
    },
    steps: ["Upload", "Extract", "Verify", "Predict"],
    home: { 
      howTitle: "One document. A clearer decision context.", 
      howBody: "A continuous path from application image to an understandable prediction.", 
      pipeline: "Intelligence pipeline", 
      why: "Designed for clarity at every step", 
      whyItems: ["Human review stays in control", "Structured, ML-ready extraction", "Transparent prediction context"], 
      final: "Turn an application into insight.", 
      finalBody: "Begin with a clear image. MUSTAWFI handles the path to prediction." 
    },
    analyze: { 
      eyebrow: "Secure document intake", 
      title: "Upload your loan application", 
      body: "Use a clear image showing the complete application.", 
      drop: "Drop your application here", 
      browse: "Browse files", 
      camera: "Use camera", 
      support: "JPG, PNG or WEBP · up to 10 MB", 
      ready: "Ready for analysis", 
      action: "Analyze document", 
      remove: "Remove file" 
    },
    processing: { 
      title: "Reading your application", 
      body: "MUSTAWFI is aligning the document and structuring its information.", 
      stages: ["Image detected", "Form aligned", "Information extracted", "Validating information", "Preparing prediction"],
      emptyTitle: "No application selected",
      emptyAction: "Upload application"
    },
    review: { 
      title: "Review extracted information", 
      body: "Make sure the extracted information is correct before running the prediction.", 
      sections: ["Personal information", "Loan information", "Credit information"], 
      edit: "Edit", 
      save: "Save", 
      verified: "Verified", 
      needs: "Needs review", 
      action: "Run prediction",
      eyebrow: "HUMAN CHECKPOINT",
      emptyTitle: "No extracted application",
      emptyAction: "Upload application"
    },
    result: { 
      eyebrow: "Machine learning prediction", 
      eligible: "ELIGIBLE", 
      not_eligible: "NOT ELIGIBLE", 
      low_confidence: "LOW CONFIDENCE", 
      error: "UNAVAILABLE", 
      confidence: "Confidence", 
      note: "This result is generated by the machine learning system and does not represent a final banking decision.", 
      why: "Prediction context", 
      whyBody: "A visual summary of the application data considered by the model. These indicators do not imply causality.", 
      summary: "Application summary", 
      report: "Download report", 
      again: "Analyze another",
      emptyTitle: "No prediction available",
      emptyAction: "Analyze application"
    },
    about: { 
      eyebrow: "About MUSTAWFI", 
      title: "Intelligence with a human checkpoint.", 
      body: "MUSTAWFI turns loan application images into structured information, then gives people a clear opportunity to verify it before prediction.", 
      items: [
        ["What is MUSTAWFI?", "A focused document intelligence experience for understanding loan eligibility signals."], 
        ["Computer vision", "The application image is aligned and read into structured, reviewable fields."], 
        ["Machine learning", "Verified application data is passed to a separate prediction service through a secure API."], 
        ["Privacy & data handling", "The interface keeps data use visible and limits every step to the application journey."]
      ] 
    },
    errors: { 
      invalid: "Choose a JPG, PNG or WEBP image.", 
      large: "The file must be smaller than 10 MB.", 
      general: "We couldn't read this document", 
      detail: "Try uploading a clearer image with the complete application visible.", 
      retry: "Upload another document" 
    },
    notFound: { 
      title: "Page not found", 
      body: "The page you're looking for doesn't exist or has been moved.", 
      action: "Go home" 
    },
    errorPage: { 
      title: "This page didn't load", 
      body: "Something went wrong on our end. You can try refreshing or head back home.", 
      retry: "Try again", 
      home: "Go home" 
    },
  },
  ar: {
    nav: { how: "ازاي بيشتغل", analyze: "حلل الطلب", about: "عن مستوف" },
    hero: { 
      eyebrow: "ذكاء المستندات.. ببساطة وبشكل أوضح", 
      title: "اعرف أهليتك للقرض بذكاء وسرعة.", 
      body: "ارفع صورة طلب القرض، وسيب 'مُســـــتوفٍ' يحلل بياناتك، ويتحقق منها، ويحولها لتوقع ذكي بالذكاء الاصطناعي.", 
      primary: "ابدأ تحليل الطلب", 
      secondary: "ازاي بيشتغل" 
    },
    steps: ["ارفع الطلب", "استخراج البيانات", "مراجعة وتأكيد", "اعرف النتيجة"],
    home: { 
      howTitle: "مستند واحد.. والرؤية تبقى واضحة قدامك.", 
      howBody: "رحلة متصلة من صورة الطلب لحد ما تاخد توقع مفهوم وواضح.", 
      pipeline: "خطوات التحليل", 
      why: "كل خطوة مصممة علشان تكون واضحة ومريحة", 
      whyItems: ["القرار الأخير دايماً في إيدك (مراجعة بشرية أكيدة)", "استخراج منظم وجاهز للشغل فوراً", "سياق واضح وشفاف لكل توقع"], 
      final: "جاهز تحول طلبك لمعلومة مفيدة؟", 
      finalBody: "ابدأ برفع صورة واضحة، وسيب 'مُســـــتوفٍ' يكمل الباقي." 
    },
    analyze: { 
      eyebrow: "رفع آمن للملفات", 
      title: "ارفع طلب القرض بتاعك", 
      body: "اتأكد إن الصورة واضحة والطلب باين فيها كله.", 
      drop: "اسحب الطلب وحطه هنا", 
      browse: "تصفح الملفات", 
      camera: "صور بالكاميرا", 
      support: "JPG أو PNG أو WEBP · بحد أقصى 10 ميجابايت", 
      ready: "الملف جاهز للتحليل", 
      action: "ابدأ تحليل المستند", 
      remove: "احذف الملف" 
    },
    processing: { 
      title: "جاري قراءة طلبك...", 
      body: "مستوف بيظبط الصورة وينظم كل معلومة فيها.", 
      stages: ["تم التعرف على الصورة", "تمت محاذاة النموذج", "تم استخراج البيانات بنجاح", "جارٍ التحقق من صحة البيانات", "تجهيز النتيجة والتوقع"],
      emptyTitle: "لم يتم اختيار طلب",
      emptyAction: "ارفع الطلب"
    },
    review: { 
      title: "راجع البيانات المستخرجة", 
      body: "بص بصة سريعة واتأكد إن كل حاجة مظبوطة قبل ما نظهر النتيجة.", 
      sections: ["المعلومات الشخصية", "بيانات القرض", "البيانات الائتمانية"], 
      edit: "تعديل", 
      save: "حفظ التعديلات", 
      verified: "تم التحقق", 
      needs: "محتاج مراجعة", 
      action: "اظهار التوقع",
      eyebrow: "مراجعة بشرية",
      emptyTitle: "لا يوجد طلب مستخرج",
      emptyAction: "ارفع الطلب"
    },
    result: { 
      eyebrow: "نتيجة التوقع الذكي", 
      eligible: "مؤهل للحصول على القرض", 
      not_eligible: "غير مؤهل", 
      low_confidence: "نسبة ثقة منخفضة", 
      error: "غير متوفر حالياً", 
      confidence: "مستوى الثقة", 
      note: "النتيجة دي مولدة بواسطة نظام الذكاء الاصطناعي، وماتعتبرش قرار نهائي من البنك.", 
      why: "تفاصيل التوقع", 
      whyBody: "ملخص سريع للبيانات اللي اتعمدنا عليها في التحليل. المؤشرات دي بتوضح الصورة بس مش سبب مباشر لوحدها.", 
      summary: "ملخص الطلب", 
      report: "تحميل التقرير", 
      again: "افحص طلب تاني",
      emptyTitle: "لا توجد نتيجة متاحة",
      emptyAction: "حلل طلب جديد"
    },
    about: { 
      eyebrow: "عن مستوف", 
      title: "ذكاء ذكي.. بلمسة مراجعة بشرية.", 
      body: "مستوف بيحول صور طلبات القروض لبيانات مترَتّبة وواضحة، وبيديك فرصة تراجعها بنفسك بكل سهولة قبل ما نتوقع النتيجة.", 
      items: [
        ["إيه هو مستوف؟", "أداة ذكية متخصصة في قراءة وفهم مستندات طلبات القروض بسهولة."], 
        ["الرؤية الحاسوبية", "بناخد صورة الطلب نظبطها ونقراها ونحولها لبيانات جاهزة للمراجعة."], 
        ["تعلم الآلة", "بنبعت البيانات اللي راجعتها لخدمة توقع متقدمة ومؤمنة تماماً."], 
        ["الخصوصية والأمان", "بياناتك في أمان، واستخدامها محصور فقط في رحلة الطلب بتاعتك."]
      ] 
    },
    errors: { 
      invalid: "من فضلك اختار صورة بصيغة JPG أو PNG أو WEBP.", 
      large: "حجم الملف كبير جداً، لازم يكون أقل من 10 ميجابايت.", 
      general: "مش قادرين نقرا الملف للأسف.", 
      detail: "جرب ترفع صورة أوضح يكون فيها الطلب ظاهر بالكامل.", 
      retry: "جرب ترفع ملف تاني" 
    },
    notFound: { 
      title: "الصفحة غير موجودة", 
      body: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.", 
      action: "الرئيسية" 
    },
    errorPage: { 
      title: "لم يتم تحميل هذه الصفحة", 
      body: "حدث خطأ ما من طرفنا. يمكنك محاولة تحديث الصفحة أو العودة للرئيسية.", 
      retry: "حاول مرة أخرى", 
      home: "الرئيسية" 
    },
  },
} as const;